title: FD JAPON
email: fd_multimedia@avrt.fr
description: >- # this means to ignore newlines until "baseurl:"
  Cours de japonais
  Aide au voyage ou à la vie au japon
  Traduction du japonais vers le français et du japonais vers l'anglais
domain: fdjapon.github.io 
baseurl: "/" 
url: "https://fdjapon.github.io" 
